#!/bin/sh -e
#
# Build docs.

rm -fr docs

find site -type f | while read -r file; do
    docs=docs/${file#*/}
    mkdir -p "${docs%/*}"

    case $file in
        *.txt) cat temp/a "$file" temp/b > "${docs%.*}.html" ;;
        *)     cp -f "$file" "$docs" ;;
    esac
done

# printf lieu.cf > docs/CNAME
